dist: bionic
language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master

before_install:
  - travis_retry composer self-update
  - composer install --no-interaction --no-suggest --prefer-source --dev

script:
  - composer test -- --coverage-clover=coverage.xml

after_success:
  # Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)

#matrix:
#  allow_failures:
#    - php: nightly
#  fast_finish: true
